****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZJSRPT_004																																
9000																																
752																																
                40																																
%_HEADER																																
ZJSRPT_004                              9000 9000     30170192 37  0  0 35170  0G 1                              20191016190725																																
%_DESCRIPTION																																
运费处理屏幕																																
%_FIELDS																																
ZSVAT_YFCL_H-ZYF	0	CHAR	  5	30	00	00	30	00	  2	  6		  0	  0	  0		  0					  0	  0								运费	                                                                                                                                                                                                                                                        X	
ZSVAT_YFCL_H-ZYF	P	CURR	 16	A0	00	80	00	00	  2	 14		  0	  0	  0		  0					 13	  2		ZSVAT_YFCL_H-WAERS						________________	                                       00	
ZSVAT_YFCL_H-ZBF	0	CHAR	  5	30	00	00	30	00	  2	 41		  0	  0	  0		  0					  0	  0								保费	                                                                                                                                                                                                                                                        X	
ZSVAT_YFCL_H-ZBF	P	CURR	 16	A0	00	80	00	00	  2	 50		  0	  0	  0		  0					 13	  2		ZSVAT_YFCL_H-WAERS						________________	                                       00	
ZSVAT_YFCL_H-WAERS	0	CHAR	  5	30	00	00	30	00	  2	 84		  0	  0	  0		  0			FWS		  0	  0								货币	                                                                                                                                                                                                                                                        X	
ZSVAT_YFCL_H-WAERS	C	CUKY	  5	A0	0C	80	00	08	  2	 91		  0	  0	  0		  7			FWS		 10	  0								_____	 DL                                    00	
ZSVAT_YFCL_H-ZJGTK	0	CHAR	  8	30	00	00	30	00	  2	118		  0	  0	  0		  0					  0	  0								价格条款	                                                                                                                                                                                                                                                        X	
ZSVAT_YFCL_H-ZJGTK	C	CHAR	 16	B0	00	80	00	00	  2	131		  0	  0	  0		  0					 40	  0								________________	                                       00	
ZTRCL_YF			170	F4	F0	00	00	00	  4	  2	E	101	  1	  1		 20	T				  5	 15										
GS_YF_ITEM-ZIDNUM		CHAR	 15	00	00	08	30	80	  1	  1	T	101	  1	  1		 15					  0	  0								样票号码		
GS_YF_ITEM-ZPOSNR		CHAR	 10	00	00	08	30	80	  1	  2	T	101	  1	  1		 10					  0	  0								样票行项目		
GS_YF_ITEM-ZSPMC		CHAR	 54	00	00	08	30	80	  1	  3	T	101	  1	  1		 23					  0	  0								物品名称		
GS_YF_ITEM-ZGGXH		CHAR	 31	00	00	08	30	80	  1	  4	T	101	  1	  1		 18					  0	  0								规格型号		
GS_YF_ITEM-ZMONNT	0	CHAR	 20	00	00	00	30	80	  1	  5	T	101	  1	  1		 14					  0	  0								金额		
GS_YF_ITEM-WAERK	0	CHAR	  4	00	00	00	30	80	  1	  6	T	101	  1	  1		  5					  0	  0								货币		
GS_YF_ITEM-BEZEI		CHAR	 37	00	00	08	30	80	  1	  7	T	101	  1	  1		 11					  0	  0								贸易方式		
GS_YF_ITEM-ZBMOUNT		CHAR	 16	00	00	08	30	80	  1	  8	T	101	  1	  1		 14					  0	  0								本位币金额		
GS_YF_ITEM-ZWAERK		CHAR	 10	00	00	08	30	80	  1	  9	T	101	  1	  1		 10					  0	  0								本位币货币		
GS_YF_ITEM-FKIMG		CHAR	 10	00	00	08	30	80	  1	 10	T	101	  1	  1		 13					  0	  0								数量		
GS_YF_ITEM-KURSK		CHAR	  8	00	00	08	30	80	  1	 11	T	101	  1	  1		  7					  0	  0								汇率		
GS_YF_ITEM-ZFOB_PRICE		CHAR	  7	00	00	08	30	80	  1	 12	T	101	  1	  1		 16					  0	  0								FOB价		
GS_YF_ITEM-ZIDNUM		CHAR	 15	80	00	88	30	00	  1	  1	T	101	  1	  1		 15					  0	  0								_______________		
GS_YF_ITEM-ZPOSNR		NUMC	  6	80	00	88	30	00	  1	  2	T	101	  1	  1		 10					  0	  0								______		
GS_YF_ITEM-ZSPMC		CHAR	 60	81	00	88	30	00	  1	  3	T	101	  1	  1		 23					  0	  0								____________________________________________________________		
GS_YF_ITEM-ZGGXH		CHAR	 32	81	00	88	30	00	  1	  4	T	101	  1	  1		 18					  0	  0								________________________________		
GS_YF_ITEM-ZMOUNT	P	CURR	 20	80	00	80	30	00	  1	  5	T	101	  1	  1		 14					 15	  2		ZSVAT_YFCL_I-WAERK						____________________		
GS_YF_ITEM-WAERK	C	CUKY	  5	80	00	80	30	00	  1	  6	T	101	  1	  1		  5			FWS		  5	  0								_____		
GS_YF_ITEM-BEZEI		CHAR	 40	81	00	88	30	00	  1	  7	T	101	  1	  1		 11					  0	  0								________________________________________		
GS_YF_ITEM-ZBMOUNT		DEC	 20	80	00	88	30	00	  1	  8	T	101	  1	  1		 14					  0	  0								____________________		
GS_YF_ITEM-ZWAERK		CHAR	  5	80	00	88	30	00	  1	  9	T	101	  1	  1		 10					  0	  0								_____		
GS_YF_ITEM-FKIMG		DEC	 17	80	00	88	30	00	  1	 10	T	101	  1	  1		 13					  0	  0								_________________		
GS_YF_ITEM-KURSK		DEC	 12	80	00	88	30	00	  1	 11	T	101	  1	  1		  7					  0	  0								____________		
GS_YF_ITEM-ZFOB_PRICE		DEC	 16	80	00	88	00	00	  1	 12	T	101	  1	  1		 16					  0	  0										
BUTTON1		CHAR	  8	00	00	00	30	00	 24	 15		  0	  0	  0		  0	P				  0	  0	102							模拟分摊	                                                                                                                                                                        TEST	
BUTTON2		CHAR	  8	00	00	00	30	00	 24	 66		  0	  0	  0		  0	P				  0	  0	103							确定分摊	                                                                                                                                                                        CONFIRM	
BUTTON3		CHAR	  4	00	00	00	30	00	 24	121		  0	  0	  0		  0	P				  0	  0	104							取消	                                                                                                                                                                        CANCEL	
ZBEIZHU			167	00	00	00	30	00	 25	  4		  0	  0	  0		  6	U				  1	  1	105									
OK_CODE		CHAR	 20	80	10	08	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'ZTRCL_YF'																																
  MODULE ZTRCL_YF_CHANGE_TC_ATTR.																																
*&SPWIZARD: MODULE ZTRCL_YF_CHANGE_COL_ATTR.																																
  LOOP AT   GT_YF_ITEM																																
       INTO GS_YF_ITEM																																
       WITH CONTROL ZTRCL_YF																																
       CURSOR ZTRCL_YF-CURRENT_LINE.																																
    MODULE ZTRCL_YF_GET_LINES.																																
*&SPWIZARD:   MODULE ZTRCL_YF_CHANGE_FIELD_ATTR																																
  ENDLOOP.																																
																																
 MODULE STATUS_9000.																																
*																																
PROCESS AFTER INPUT.																																
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'ZTRCL_YF'																																
  LOOP AT GT_YF_ITEM.																																
    CHAIN.																																
      FIELD GS_YF_ITEM-ZIDNUM.																																
      FIELD GS_YF_ITEM-ZPOSNR.																																
      FIELD GS_YF_ITEM-ZSPMC.																																
      FIELD GS_YF_ITEM-ZGGXH.																																
      FIELD GS_YF_ITEM-BEZEI.																																
      FIELD GS_YF_ITEM-ZBMOUNT.																																
      FIELD GS_YF_ITEM-ZWAERK.																																
      FIELD GS_YF_ITEM-FKIMG.																																
      FIELD GS_YF_ITEM-KURSK.																																
      FIELD GS_YF_ITEM-ZFOB_PRICE.																																
      MODULE ZTRCL_YF_MODIFY ON CHAIN-REQUEST.																																
    endchain.																																
  ENDLOOP.																																
																																
  MODULE ZTRCL_YF_USER_COMMAND.																																
*&SPWIZARD: MODULE ZTRCL_YF_CHANGE_TC_ATTR.																																
*&SPWIZARD: MODULE ZTRCL_YF_CHANGE_COL_ATTR.																																
																																
 MODULE USER_COMMAND_9000.																																
																																
PROCESS ON VALUE-REQUEST.																																
																																
  FIELD ZSVAT_YFCL_H-WAERS MODULE WAERS_F4.																																
